language: python

sudo: true
fast_finish: true

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
      dist: xenial
      sudo: true

install:
  - pip install poetry
  - poetry install

script:
  - poetry run pytest --cov=quantstats

after_success:
  - poetry run coveralls

branches:
  only:
    - main

notifications:
  slack: tradologics:HcnS6XusfcuS02waQPCG18oc
  webhooks:
    urls:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
